/*
 * Copyright (c) 2025 curioloop. All rights reserved.
 */
package com.curioloop.yum4j.linalg;

import org.junit.jupiter.api.Test;

import com.curioloop.yum4j.fixtures.StatsmodelsResources;
import com.curioloop.yum4j.linalg.reg.Prediction;
import com.curioloop.yum4j.linalg.reg.WLS;
import com.curioloop.yum4j.linalg.reg.OLS;

import static java.lang.Math.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for OLS and WLS against scipy/statsmodels reference values.
 *
 * <p>Sample: 50 obs, true model y = 2x + 1 + N(0,1.5), generated by
 * numpy.random.default_rng(42).normal(0, 1.5, 50).
 * Weights: w[i]=1 for i<30, w[i]=3 for i>=30; wInv[i]=1/w[i].
 */
public class RegressorTest {

    static final int NOBS = 50;

    // x = np.linspace(0, 20, 50)
    static final double[] X_VEC = {
        0.0, 0.40816326530612246, 0.8163265306122449, 1.2244897959183674,
        1.6326530612244898, 2.0408163265306123, 2.4489795918367347, 2.857142857142857,
        3.2653061224489797, 3.673469387755102, 4.081632653061225, 4.4897959183673475,
        4.8979591836734695, 5.3061224489795915, 5.714285714285714, 6.122448979591837,
        6.530612244897959, 6.938775510204081, 7.346938775510204, 7.755102040816327,
        8.16326530612245, 8.571428571428571, 8.979591836734695, 9.387755102040817,
        9.795918367346939, 10.204081632653061, 10.612244897959183, 11.020408163265307,
        11.428571428571429, 11.83673469387755, 12.244897959183675, 12.653061224489797,
        13.061224489795919, 13.46938775510204, 13.877551020408163, 14.285714285714286,
        14.693877551020408, 15.10204081632653, 15.510204081632654, 15.918367346938776,
        16.3265306122449, 16.73469387755102, 17.142857142857142, 17.551020408163264,
        17.95918367346939, 18.367346938775512, 18.775510204081634, 19.183673469387756,
        19.591836734693878, 20.0
    };

    // y = 2*x + 1 + rng.normal(0, 1.5, 50)  [numpy rng(42)]
    static final double[] Y_VEC = {
        1.457075619631647, 0.2563503712515016, 3.7583298549341757, 4.859826666423555,
        1.3387533394682252, 3.1283633927677474, 6.089719788424397, 6.239921825770341,
        7.505410508641526, 7.067372884149833, 10.482362268416692, 11.146279739878118,
        10.894964413688763, 13.303106708411232, 13.129835441949497, 11.955959264858818,
        14.614350665919666, 13.439227119164665, 17.011553002981316, 16.435315215153274,
        17.049237066927006, 17.121462826251232, 20.792995681480434, 19.54371598097843,
        19.949345001449217, 20.879962939573776, 23.02295357424839, 23.588982423076732,
        24.47624177453684, 25.319700892266926, 28.70226731967304, 25.69649992440267,
        26.35408488598453, 26.718116417832263, 29.679071174679567, 31.26488701050991,
        30.216833915558503, 29.943846917209267, 30.783686339728447, 33.812623875614605,
        34.76794248129496, 35.284119157559836, 34.28744972478124, 36.45028280092661,
        37.09339606064987, 38.062726772644545, 39.858163575085555, 39.702740261937535,
        41.2020438139956, 41.101368604233336
    };


    /** Build X=[x,1] row-major n×2. */
    static double[] buildX2() {
        double[] X = new double[NOBS * 2];
        for (int i = 0; i < NOBS; i++) { X[i*2] = X_VEC[i]; X[i*2+1] = 1.0; }
        return X;
    }

    /** weights: 1 for i<30, 3 for i>=30; wInv = 1/w. */
    static double[] buildWInv() {
        double[] wInv = new double[NOBS];
        for (int i = 0; i < NOBS; i++) wInv[i] = (i < 30) ? 1.0 : 1.0/3.0;
        return wInv;
    }

    static void assertClose(double[] expected, double[] actual, double tol, String msg) {
        assertEquals(expected.length, actual.length, msg + " length");
        for (int i = 0; i < expected.length; i++)
            assertEquals(expected[i], actual[i], tol, msg + "[" + i + "]");
    }

    // ================================================================
    // OLS — SVD
    // scipy: beta=[2.0339267718, 0.7975488276], SSR=63.0784, R²=0.9913,
    //        scale=1.3141, llf=-76.7558, aic=157.5116, bic=161.3356
    //        bse=[0.0275237879, 0.3194347290]
    // ================================================================

    @Test
    void testOLS_SVD_basicStats() {
        Regression res = new OLS(Y_VEC, buildX2(), NOBS, 2, false, -1).fit();

        assertEquals(2, res.rank());
        double[] beta = res.params();
        assertEquals(2.033926771810814,  beta[0], 1e-12, "OLS SVD beta[0]");
        assertEquals(0.7975488276313836, beta[1], 1e-12, "OLS SVD beta[1]");

        assertEquals(63.078373945217308, res.ssr(),      1e-12, "OLS SVD SSR");
        assertEquals(0.991286627798468,  res.r2(false),  1e-12, "OLS SVD R²");
        assertEquals(0.991105099210936,  res.r2(true),   1e-12, "OLS SVD R²adj");
        assertEquals(1.314132790525361,  res.scale(),    1e-12, "OLS SVD scale");
        assertEquals(-76.755801127098692, res.logLike(), 1e-12, "OLS SVD llf");
        assertEquals(157.511602254197385, res.aic(),     1e-12, "OLS SVD aic");
        assertEquals(161.335648265053663, res.bic(),     1e-12, "OLS SVD bic");

        double[] bse = res.bse();
        assertEquals(0.027523787943766802, bse[0], 1e-12, "OLS SVD bse[0]");
        assertEquals(0.31943472899459685,  bse[1], 1e-12, "OLS SVD bse[1]");
        assertEquals(2, bse.length);
        assertEquals(4, res.paramCov().length);
    }

    // ================================================================
    // OLS — QR: same beta/SSR/R²/scale/llf/aic/bic/bse as SVD
    // ================================================================

    @Test
    void testOLS_QR_basicStats() {
        Regression res = new OLS(Y_VEC, buildX2(), NOBS, 2, true, -1).fit();

        assertEquals(2, res.rank());
        double[] beta = res.params();
        assertEquals(2.033926771810814,  beta[0], 1e-12, "OLS QR beta[0]");
        assertEquals(0.7975488276313836, beta[1], 1e-12, "OLS QR beta[1]");

        assertEquals(63.078373945217308, res.ssr(),      1e-12, "OLS QR SSR");
        assertEquals(0.991286627798468,  res.r2(false),  1e-12, "OLS QR R²");
        assertEquals(0.991105099210936,  res.r2(true),   1e-12, "OLS QR R²adj");
        assertEquals(1.314132790525361,  res.scale(),    1e-12, "OLS QR scale");
        assertEquals(-76.755801127098692, res.logLike(), 1e-12, "OLS QR llf");
        assertEquals(157.511602254197385, res.aic(),     1e-12, "OLS QR aic");
        assertEquals(161.335648265053663, res.bic(),     1e-12, "OLS QR bic");

        double[] bse = res.bse();
        assertEquals(0.027523787943766802, bse[0], 1e-12, "OLS QR bse[0]");
        assertEquals(0.31943472899459685,  bse[1], 1e-12, "OLS QR bse[1]");
    }

    @Test
    void testOLS_QR_matchesSVD() {
        Regression svd = new OLS(Y_VEC, buildX2(), NOBS, 2, false, -1).fit();
        Regression qr  = new OLS(Y_VEC, buildX2(), NOBS, 2, true, -1).fit();

        assertClose(svd.params(), qr.params(), 1e-12, "OLS beta SVD vs QR");
        assertEquals(svd.ssr(),      qr.ssr(),      1e-12, "OLS SSR SVD vs QR");
        assertEquals(svd.r2(false),  qr.r2(false),  1e-12, "OLS R² SVD vs QR");
        assertEquals(svd.scale(),    qr.scale(),    1e-12, "OLS scale SVD vs QR");
        assertEquals(svd.logLike(),  qr.logLike(),  1e-12, "OLS llf SVD vs QR");
        assertClose(svd.bse(),       qr.bse(),      1e-12, "OLS bse SVD vs QR");
    }


    @Test
    void testOLS_fittedResidualConsistency() {
        Regression res = new OLS(Y_VEC, buildX2(), NOBS, 2, false, -1).fit();
        double[] fitted   = res.fitted(false);
        double[] residual = res.residual(false);

        // scipy: fitted[0]=0.7975488276, resid[0]=0.6595267920
        assertEquals(0.797548827631384, fitted[0],   1e-12, "OLS fitted[0]");
        assertEquals(0.659526792000263, residual[0], 1e-12, "OLS resid[0]");

        for (int i = 0; i < NOBS; i++)
            assertEquals(Y_VEC[i], fitted[i] + residual[i], 1e-10, "y != fitted+resid at " + i);

        double ssrManual = 0;
        for (double e : residual) ssrManual += e * e;
        assertEquals(ssrManual, res.ssr(), 1e-12, "OLS SSR manual");
    }

    @Test
    void testOLS_informationCriteria() {
        Regression res = new OLS(Y_VEC, buildX2(), NOBS, 2, false, -1).fit();
        assertTrue(Double.isFinite(res.logLike()), "llf not finite");
        assertTrue(res.bic() > res.aic(), "BIC should exceed AIC for n=50");
    }

    // ================================================================
    // OLS prediction interval — SVD
    // scipy: t_{48,0.975}=2.0106347576242318
    //   pred[0]:  std=1.190029972989, lb=-1.595166798676, ub=3.190264453939
    //   pred[49]: std=1.190029972989, lb=39.083368637540, ub=43.868799890155
    // ================================================================

    @Test
    void testOLS_predictionInterval_SVD() {
        double[] X2 = buildX2();
        Regression res = new OLS(Y_VEC, X2.clone(), NOBS, 2, false, -1).fit();

        double[] paramCov = res.paramCov();
        double[] fitted   = res.fitted(false);
        double   mse      = res.mse()[1];
        double   Q        = 2.0106347576242318; // scipy t_{48,0.975}

        int k = 2;
        double[] std = new double[NOBS], lb = new double[NOBS], ub = new double[NOBS];
        double[] tmp = new double[k];
        for (int i = 0; i < NOBS; i++) {
            for (int j = 0; j < k; j++) {
                double dot = 0;
                for (int l = 0; l < k; l++) dot += paramCov[j*k+l] * X2[i*k+l];
                tmp[j] = dot;
            }
            double pv = 0;
            for (int j = 0; j < k; j++) pv += tmp[j] * X2[i*k+j];
            std[i] = sqrt(mse + pv);
            lb[i]  = fitted[i] - Q * std[i];
            ub[i]  = fitted[i] + Q * std[i];
        }

        // scipy spot-checks
        assertEquals(1.190029972989, std[0],  1e-10, "OLS std[0]");
        assertEquals(-1.595166798676, lb[0],  1e-10, "OLS lb[0]");
        assertEquals(3.190264453939,  ub[0],  1e-10, "OLS ub[0]");
        assertEquals(39.083368637540, lb[49], 1e-10, "OLS lb[49]");
        assertEquals(43.868799890155, ub[49], 1e-10, "OLS ub[49]");

        Prediction pred = res.predict(X2, NOBS, null);
        double[][] ci = pred.confInt(0.05);
        assertClose(std, ci[2], 1e-12, "OLS pred std");
        assertClose(lb,  ci[0], 1e-10, "OLS pred lb");
        assertClose(ub,  ci[1], 1e-10, "OLS pred ub");
        for (int i = 0; i < NOBS; i++)
            assertTrue(ci[0][i] < fitted[i] && fitted[i] < ci[1][i], "OLS fitted not in CI at " + i);
    }

    // ================================================================
    // OLS prediction interval — QR (must match SVD)
    // ================================================================

    @Test
    void testOLS_predictionInterval_QR() {
        double[] X2 = buildX2();
        Regression svd = new OLS(Y_VEC, X2.clone(), NOBS, 2, false, -1).fit();
        Regression qr  = new OLS(Y_VEC, X2.clone(), NOBS, 2, true, -1).fit();

        Prediction pSvd = svd.predict(X2, NOBS, null);
        Prediction pQr  = qr.predict(X2, NOBS, null);

        double[][] ciSvd = pSvd.confInt(0.05);
        double[][] ciQr  = pQr.confInt(0.05);

        assertClose(ciSvd[0], ciQr[0], 1e-10, "OLS QR pred lb");
        assertClose(ciSvd[1], ciQr[1], 1e-10, "OLS QR pred ub");
        assertClose(ciSvd[2], ciQr[2], 1e-12, "OLS QR pred std");
    }


    // ================================================================
    // WLS — SVD
    // scipy (weights=wInv): beta=[2.0398186743, 0.7664097139]
    //   SSR=46.4974, R²=0.9887, scale=0.9687, llf=-80.1174, aic=164.2348, bic=168.0589
    //   bse=[0.0314510887, 0.2935886856]
    // ================================================================

    @Test
    void testWLS_SVD_basicStats() {
        Regression res = new WLS(Y_VEC, buildX2(), buildWInv(), NOBS, 2, false, -1).fit();

        assertEquals(2, res.rank());
        double[] beta = res.params();
        assertEquals(2.0398186742701783, beta[0], 1e-12, "WLS SVD beta[0]");
        assertEquals(0.7664097138967324, beta[1], 1e-12, "WLS SVD beta[1]");

        assertEquals(46.497440408681783, res.ssr(),      1e-12, "WLS SVD SSR");
        assertEquals(0.988717593620322,  res.r2(false),  1e-12, "WLS SVD R²");
        assertEquals(0.968696675180870,  res.scale(),    1e-12, "WLS SVD scale");
        assertEquals(-80.117406063803486, res.logLike(), 1e-12, "WLS SVD llf");
        assertEquals(164.234812127606972, res.aic(),     1e-12, "WLS SVD aic");
        assertEquals(168.058858138463250, res.bic(),     1e-12, "WLS SVD bic");

        double[] bse = res.bse();
        assertEquals(0.03145108865518003,  bse[0], 1e-12, "WLS SVD bse[0]");
        assertEquals(0.29358868558157863,  bse[1], 1e-12, "WLS SVD bse[1]");
        assertEquals(2, bse.length);
    }

    // ================================================================
    // WLS — QR: same stats as SVD
    // ================================================================

    @Test
    void testWLS_QR_basicStats() {
        Regression res = new WLS(Y_VEC, buildX2(), buildWInv(), NOBS, 2, true, -1).fit();

        assertEquals(2, res.rank());
        double[] beta = res.params();
        assertEquals(2.0398186742701783, beta[0], 1e-12, "WLS QR beta[0]");
        assertEquals(0.7664097138967324, beta[1], 1e-12, "WLS QR beta[1]");

        assertEquals(46.497440408681783, res.ssr(),      1e-12, "WLS QR SSR");
        assertEquals(0.988717593620322,  res.r2(false),  1e-12, "WLS QR R²");
        assertEquals(0.968696675180870,  res.scale(),    1e-12, "WLS QR scale");
        assertEquals(-80.117406063803486, res.logLike(), 1e-12, "WLS QR llf");
        assertEquals(164.234812127606972, res.aic(),     1e-12, "WLS QR aic");
        assertEquals(168.058858138463250, res.bic(),     1e-12, "WLS QR bic");

        double[] bse = res.bse();
        assertEquals(0.03145108865518003,  bse[0], 1e-12, "WLS QR bse[0]");
        assertEquals(0.29358868558157863,  bse[1], 1e-12, "WLS QR bse[1]");
    }

    @Test
    void testWLS_QR_matchesSVD() {
        Regression svd = new WLS(Y_VEC, buildX2(), buildWInv(), NOBS, 2, false, -1).fit();
        Regression qr  = new WLS(Y_VEC, buildX2(), buildWInv(), NOBS, 2, true, -1).fit();

        assertClose(svd.params(), qr.params(), 1e-12, "WLS beta SVD vs QR");
        assertEquals(svd.ssr(),     qr.ssr(),     1e-12, "WLS SSR SVD vs QR");
        assertEquals(svd.r2(false), qr.r2(false), 1e-12, "WLS R² SVD vs QR");
        assertEquals(svd.scale(),   qr.scale(),   1e-12, "WLS scale SVD vs QR");
        assertEquals(svd.logLike(), qr.logLike(), 1e-12, "WLS llf SVD vs QR");
        assertClose(svd.bse(),      qr.bse(),     1e-12, "WLS bse SVD vs QR");
    }

    @Test
    void testWLS_fittedResidualConsistency() {
        Regression res = new WLS(Y_VEC, buildX2(), buildWInv(), NOBS, 2, false, -1).fit();
        double[] fitted   = res.fitted(false);
        double[] residual = res.residual(false);

        // scipy: fitted[0]=0.7664097139, resid[0]=0.6906659057
        assertEquals(0.766409713896732, fitted[0],   1e-12, "WLS fitted[0]");
        assertEquals(0.690665905734915, residual[0], 1e-12, "WLS resid[0]");

        for (int i = 0; i < NOBS; i++)
            assertEquals(Y_VEC[i], fitted[i] + residual[i], 1e-10, "WLS y != fitted+resid at " + i);
    }

    @Test
    void testWLS_whitenedResiduals() {
        double[] wInv = buildWInv();
        Regression res = new WLS(Y_VEC, buildX2(), wInv, NOBS, 2, false, -1).fit();
        double[] eRaw    = res.residual(false);
        double[] eWhiten = res.residual(true);

        for (int i = 0; i < NOBS; i++)
            assertEquals(eRaw[i] * sqrt(wInv[i]), eWhiten[i], 1e-12, "whitened resid at " + i);

        double ssrManual = 0;
        for (double e : eWhiten) ssrManual += e * e;
        assertEquals(ssrManual, res.ssr(), 1e-8, "WLS SSR from whitened");
    }

    // ================================================================
    // WLS prediction interval — SVD
    // scipy: pred[0]:  std=1.027078863322, lb=-1.298670747519, ub=2.831490175313
    //        pred[49]: std=1.755099364581, lb=38.033919413790, ub=45.091646984811
    // ================================================================

    @Test
    void testWLS_predictionInterval_SVD() {
        double[] X2   = buildX2();
        double[] wInv = buildWInv();
        double[] X2orig = X2.clone(); // save original X for prediction (X is overwritten by fit)
        Regression res = new WLS(Y_VEC, X2, wInv, NOBS, 2, false, -1).fit();

        double[] paramCov = res.paramCov();
        double[] fitted   = res.fitted(false);
        double   mse      = res.mse()[1];
        double   Q        = 2.0106347576242318;

        int k = 2;
        double[] std = new double[NOBS], lb = new double[NOBS], ub = new double[NOBS];
        double[] tmp = new double[k];
        for (int i = 0; i < NOBS; i++) {
            for (int j = 0; j < k; j++) {
                double dot = 0;
                for (int l = 0; l < k; l++) dot += paramCov[j*k+l] * X2orig[i*k+l];
                tmp[j] = dot;
            }
            double pv = 0;
            for (int j = 0; j < k; j++) pv += tmp[j] * X2orig[i*k+j];
            double wi = (i < 30) ? 1.0 : 3.0;
            std[i] = sqrt(mse * wi + pv);   // residualVar = scale / wInv[i] = scale * w[i]
            lb[i]  = fitted[i] - Q * std[i];
            ub[i]  = fitted[i] + Q * std[i];
        }

        // scipy spot-checks
        assertEquals(1.027078863322,  std[0],  1e-10, "WLS std[0]");
        assertEquals(-1.298670747519, lb[0],   1e-10, "WLS lb[0]");
        assertEquals(2.831490175313,  ub[0],   1e-10, "WLS ub[0]");
        assertEquals(38.033919413790, lb[49],  1e-10, "WLS lb[49]");
        assertEquals(45.091646984811, ub[49],  1e-10, "WLS ub[49]");

        Prediction pred = res.predict(X2orig, NOBS, wInv);
        double[][] ci = pred.confInt(0.05);
        assertClose(std, ci[2], 1e-12, "WLS pred std");
        assertClose(lb,  ci[0], 1e-10, "WLS pred lb");
        assertClose(ub,  ci[1], 1e-10, "WLS pred ub");
        for (int i = 0; i < NOBS; i++)
            assertTrue(ci[0][i] < fitted[i] && fitted[i] < ci[1][i], "WLS fitted not in CI at " + i);
    }

    // ================================================================
    // WLS prediction interval — QR (must match SVD)
    // ================================================================

    @Test
    void testWLS_predictionInterval_QR() {
        double[] X2   = buildX2();
        double[] wInv = buildWInv();
        Regression svd = new WLS(Y_VEC, X2,        wInv, NOBS, 2, false, -1).fit();
        Regression qr  = new WLS(Y_VEC, buildX2(), wInv, NOBS, 2, true, -1).fit();

        double[] X2orig = buildX2(); // fresh X for prediction
        Prediction pSvd = svd.predict(X2orig, NOBS, wInv);
        Prediction pQr  = qr.predict(X2orig, NOBS, wInv);

        double[][] ciSvd = pSvd.confInt(0.05);
        double[][] ciQr  = pQr.confInt(0.05);

        assertClose(ciSvd[0], ciQr[0], 1e-10, "WLS QR pred lb");
        assertClose(ciSvd[1], ciQr[1], 1e-10, "WLS QR pred ub");
        assertClose(ciSvd[2], ciQr[2], 1e-12, "WLS QR pred std");
    }


    // ================================================================
    // Numerical sanity: known exact solution
    // ================================================================

    @Test
    void testOLS_exactFit() {
        double[] X = {1, 1,  2, 1,  3, 1};
        double[] y = {3, 5, 7};
        Regression res = new OLS(y, X, 3, 2, false, -1).fit();
        assertEquals(2.0, res.params()[0], 1e-10, "slope");
        assertEquals(1.0, res.params()[1], 1e-10, "intercept");
        assertEquals(1.0, res.r2(false), 1e-10, "R²");
        assertEquals(0.0, res.ssr(),     1e-10, "SSR");
    }

    @Test
    void testWLS_uniformWeightsMatchOLS() {
        double[] X = {1,1, 2,1, 3,1, 4,1, 5,1};
        double[] y = {2.1, 4.0, 5.9, 8.1, 10.0};
        double[] w = {1, 1, 1, 1, 1};
        Regression ols = new OLS(y, X.clone(), 5, 2, false, -1).fit();
        Regression wls = new WLS(y, X, w, 5, 2, false, -1).fit();
        assertClose(ols.params(), wls.params(), 1e-10, "uniform WLS vs OLS beta");
        assertEquals(ols.ssr(),      wls.ssr(),      1e-10, "uniform WLS vs OLS SSR");
        assertEquals(ols.r2(false),  wls.r2(false),  1e-10, "uniform WLS vs OLS R²");
    }

    @Test
    void testOLS_noConstant() {
        double[] X = {1,2, 2,4, 3,6, 4,8};
        double[] y = {3, 6, 9, 12};
        assertEquals(0, new OLS(y, X, 4, 2, false, -1).fit().kConst(), "kConst should be 0");
    }

    @Test
    void testOLS_withConstant() {
        double[] X = {1,1, 2,1, 3,1, 4,1};
        double[] y = {3, 5, 7, 9};
        assertEquals(1, new OLS(y, X, 4, 2, false, -1).fit().kConst(), "kConst should be 1");
    }

    // ================================================================
    // LeastSquares facade
    // ================================================================

    @Test
    void testFacade_ols_matchesDirectOLS() {
        double[] X = buildX2();
        Regression direct = new OLS(Y_VEC, X.clone(), NOBS, 2, false, -1).fit();
        Regression facade = Regressor.ols(Y_VEC, X.clone(), NOBS, 2, Regressor.Opts.PINV);
        assertClose(direct.params(), facade.params(), 1e-10, "facade OLS beta");
        assertEquals(direct.ssr(),     facade.ssr(),     1e-10, "facade OLS SSR");
        assertEquals(direct.r2(false), facade.r2(false), 1e-10, "facade OLS R²");
    }

    @Test
    void testFacade_ols_qrOpt() {
        double[] X = buildX2();
        Regression svd = Regressor.ols(Y_VEC, X.clone(), NOBS, 2, Regressor.Opts.PINV);
        Regression qr  = Regressor.ols(Y_VEC, X.clone(), NOBS, 2, Regressor.Opts.QR);
        assertClose(svd.params(), qr.params(), 1e-10, "facade QR vs SVD beta");
        assertEquals(svd.ssr(), qr.ssr(), 1e-8, "facade QR vs SVD SSR");
    }

    @Test
    void testFacade_wls_matchesDirectWLS() {
        double[] X = buildX2(), wInv = buildWInv();
        Regression direct = new WLS(Y_VEC, X,           wInv, NOBS, 2, false, -1).fit();
        Regression facade = Regressor.wls(Y_VEC, buildX2(), wInv, NOBS, 2, Regressor.Opts.PINV);
        assertClose(direct.params(), facade.params(), 1e-10, "facade WLS beta");
        assertEquals(direct.ssr(),     facade.ssr(),     1e-10, "facade WLS SSR");
        assertEquals(direct.r2(false), facade.r2(false), 1e-10, "facade WLS R²");
    }

    @Test
    void testFacade_poolReuse() {
        WLS.Pool ws = new WLS.Pool();
        Regression r1 = Regressor.ols(Y_VEC, buildX2(), NOBS, 2, ws, Regressor.Opts.PINV);
        double[] beta1 = r1.params().clone();
        Regression r2 = Regressor.ols(Y_VEC, buildX2(), NOBS, 2, ws, Regressor.Opts.PINV);
        assertClose(beta1, r2.params(), 1e-10, "pool reuse beta");
        assertEquals(r1.ssr(), r2.ssr(), 1e-10, "pool reuse SSR");
    }

    @Test
    void testFacade_noConstDetect() {
        double[] y = {3, 5, 7, 9};
        double[] X = {1,1, 2,1, 3,1, 4,1};
        assertEquals(1, Regressor.ols(y, X.clone(), 4, 2, Regressor.Opts.PINV).kConst(),                                 "kConst auto-detect");
        assertEquals(1, Regressor.ols(y, X.clone(), 4, 2, Regressor.Opts.PINV, Regressor.Opts.HAS_CONST).kConst(),      "kConst HAS_CONST");
        assertEquals(0, Regressor.ols(y, X.clone(), 4, 2, Regressor.Opts.PINV, Regressor.Opts.NO_CONST).kConst(),       "kConst NO_CONST");
    }

    @Test
    void testFacade_yNotModified() {
        double[] y = Y_VEC.clone();
        double[] yOrig = y.clone();
        Regressor.ols(y, buildX2(), NOBS, 2, Regressor.Opts.PINV);
        assertClose(yOrig, y, 0, "y was modified");
    }

    // ================================================================
    // t-quantile accuracy
    // ================================================================

    @Test
    void testTQuantile_df48_alpha005() {
        // scipy: t_{48, 0.975} = 2.0106347576242318
        assertEquals(2.0106347576242318, Prediction.tQuantile(48, 0.975), 1e-4, "t_{48,0.975}");
    }


    // ================================================================
    // macrodata.csv real-data OLS — SVD and QR
    // scipy: beta=[-9.4817, 4.3742, -0.6140], SSR=22799.678, R²=0.6770
    //        scale=114.5712, llf=-763.9752, aic=1533.9504, bic=1543.8752
    //        bse=[1.0685, 0.2147, 0.2847]
    // ================================================================

    static java.util.Map<String, double[]> loadMacrodata() throws Exception {
        return StatsmodelsResources.readMacrodataColumns();
    }

    static double[][] buildMacrodataXY() throws Exception {
        java.util.Map<String, double[]> data = loadMacrodata();
        double[] realinv = data.get("realinv").clone();
        double[] realgdp = data.get("realgdp").clone();
        double[] realint = data.get("realint");
        int nRaw = realinv.length;
        for (int i = 0; i < nRaw; i++) {
            realinv[i] = log(realinv[i]);
            realgdp[i] = log(realgdp[i]);
        }
        int n = nRaw - 1;
        double[] y = new double[n];
        double[] X = new double[n * 3];
        for (int i = 0; i < n; i++) {
            y[i]       = (realinv[i+1] - realinv[i]) * 400.0;
            double gdp = (realgdp[i+1] - realgdp[i]) * 400.0;
            X[i*3]     = 1.0;
            X[i*3+1]   = gdp;
            X[i*3+2]   = realint[i];
        }
        return new double[][]{y, X};
    }

    @Test
    void testOLS_macrodata_SVD() throws Exception {
        double[][] xy = buildMacrodataXY();
        double[] y = xy[0]; double[] X = xy[1]; int n = y.length, k = 3;

        Regression res = new OLS(y, X, n, k, false, -1).fit();

        assertEquals(n, res.nObs()); assertEquals(k, res.nParams());

        double[] beta = res.params();
        assertEquals(-9.481672774654836,  beta[0], 1e-12, "macro SVD beta[0]");
        assertEquals( 4.374221664703201,  beta[1], 1e-12, "macro SVD beta[1]");
        assertEquals(-0.6139969694789915, beta[2], 1e-12, "macro SVD beta[2]");

        assertEquals(22799.678224562645, res.ssr(),      1e-9,  "macro SVD SSR");
        assertEquals(0.676977559431938,  res.r2(false),  1e-12, "macro SVD R²");
        assertEquals(0.673731102742812,  res.r2(true),   1e-12, "macro SVD R²adj");
        assertEquals(114.571247359611277, res.scale(),   1e-10, "macro SVD scale");
        assertEquals(-763.975218160223790, res.logLike(),1e-10, "macro SVD llf");
        assertEquals(1533.950436320447579, res.aic(),    1e-10, "macro SVD aic");
        assertEquals(1543.875239412651126, res.bic(),    1e-10, "macro SVD bic");

        double[] bse = res.bse();
        assertEquals(1.0684958066626806,  bse[0], 1e-12, "macro SVD bse[0]");
        assertEquals(0.21469411088840404, bse[1], 1e-12, "macro SVD bse[1]");
        assertEquals(0.28466805360895747, bse[2], 1e-12, "macro SVD bse[2]");

        double[] resid = res.residual(false);
        assertEquals(-2.074218307939148,  resid[0],     1e-12, "macro SVD resid[0]");
        assertEquals(-16.829092178006988, resid[1],     1e-12, "macro SVD resid[1]");
        assertEquals( 3.595227733534609,  resid[n-1],   1e-12, "macro SVD resid[-1]");

        double[] fitted = res.fitted(false);
        assertEquals(34.159290817706236, fitted[0],   1e-12, "macro SVD fitted[0]");
        assertEquals( 4.483669392150139, fitted[n-1], 1e-12, "macro SVD fitted[-1]");
    }

    @Test
    void testOLS_macrodata_QR_matchesSVD() throws Exception {
        double[][] xy = buildMacrodataXY();
        double[] y = xy[0]; double[] X = xy[1]; int n = y.length, k = 3;

        Regression svd = new OLS(y, X.clone(), n, k, false, -1).fit();
        Regression qr  = new OLS(y, X.clone(), n, k, true, -1).fit();

        assertClose(svd.params(), qr.params(), 1e-12, "macro QR vs SVD beta");
        assertEquals(svd.ssr(),      qr.ssr(),      1e-10, "macro QR vs SVD SSR");
        assertEquals(svd.r2(false),  qr.r2(false),  1e-12, "macro QR vs SVD R²");
        assertEquals(svd.scale(),    qr.scale(),    1e-10, "macro QR vs SVD scale");
        assertEquals(svd.logLike(),  qr.logLike(),  1e-10, "macro QR vs SVD llf");
        assertClose(svd.bse(),       qr.bse(),      1e-12, "macro QR vs SVD bse");

        // QR residuals/fitted must also match
        assertClose(svd.residual(false), qr.residual(false), 1e-12, "macro QR vs SVD resid");
        assertClose(svd.fitted(false),   qr.fitted(false),   1e-12, "macro QR vs SVD fitted");
    }

    @Test
    void testOLS_macrodata_fittedConsistency() throws Exception {
        double[][] xy = buildMacrodataXY();
        double[] y = xy[0]; double[] X = xy[1]; int n = y.length;

        Regression res = new OLS(y, X, n, 3, false, -1).fit();
        double[] fitted   = res.fitted(false);
        double[] residual = res.residual(false);

        for (int i = 0; i < n; i++)
            assertEquals(y[i], fitted[i] + residual[i], 1e-10, "y != fitted+resid at " + i);

        double ssrManual = 0;
        for (double e : residual) ssrManual += e * e;
        assertEquals(ssrManual, res.ssr(), 1e-10, "macro SSR manual");

        double r2 = res.r2(false);
        assertTrue(r2 > 0 && r2 < 1, "R² out of range: " + r2);
    }
}
