package com.curioloop.yum4j.stats.tool;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import com.curioloop.yum4j.math.Double2;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Data-driven tests for {@code com.curioloop.yum4j.stats.tool}, mirroring the
 * statsmodels test suite structure.
 *
 * <h2>Data sources</h2>
 * <ul>
 *   <li>{@code reference/tsa/_data_/macrodata.csv} — 203-row US macroeconomic
 *       dataset (same as {@code statsmodels.datasets.macrodata})</li>
 *   <li>{@code reference/statsmodels/…/results/results_corrgram.csv} — ACF/PACF
 *       reference values generated by Stata (40 lags of {@code realgdp})</li>
 *   <li>{@code reference/statsmodels/…/results/results_ccf.csv} — CCF reference
 *       values (20 lags of {@code unemp.diff} vs {@code infl.diff})</li>
 * </ul>
 *
 * <h2>Reference tools</h2>
 * <ul>
 *   <li>Stata (ACF/PACF via {@code corrgram.do})</li>
 * </ul>
 */
class StatsToolTest {

    // ── Precision constants ───────────────────────────────────────────────────
    /** 8 decimal places — matches statsmodels DECIMAL_8 for ACF/PACF. */
    private static final double TOL8  = 1.5e-8;
    /** 6 decimal places — matches statsmodels DECIMAL_6 for PACF OLS. */
    private static final double TOL6  = 1.5e-6;
    /** 3 decimal places — matches statsmodels DECIMAL_3 for Q-statistics. */
    private static final double TOL3  = 1.5e-3;
    /** 12 decimal places — matches statsmodels decimal=(12,12) for diagnostics. */
    private static final double TOL12 = 1.5e-12;

    // ── Shared data loaded once ───────────────────────────────────────────────
    private static double[] realgdp;
    private static double[] unempDiff;
    private static double[] inflDiff;

    // ── Reference fixture arrays ──────────────────────────────────────────────
    private static double[] refAcf;        // results_corrgram.csv "acvar"  (40 values)
    private static double[] refAcfFft;     // results_corrgram.csv "acvarfft"
    private static double[] refQStat;      // results_corrgram.csv "Q1"
    private static double[] refPacfOls;    // results_corrgram.csv "PACOLS"
    private static double[] refPacfYw;     // results_corrgram.csv "PACYW"
    private static double[] refConfLb;     // results_corrgram.csv "acvar_lb" (centered)
    private static double[] refConfUb;     // results_corrgram.csv "acvar_ub" (centered)
    private static double[] refCcf;        // results_ccf.csv "ccf" (20 values)

    @BeforeAll
    static void loadFixtures() {
        // ── macrodata ─────────────────────────────────────────────────────────
        Map<String, double[]> macro = CsvFixtures.loadColumnar(
                "statsmodels/datasets/macrodata/macrodata.csv");
        realgdp = macro.get("realgdp");

        double[] unemp = macro.get("unemp");
        double[] infl  = macro.get("infl");
        unempDiff = diff(unemp);
        inflDiff  = diff(infl);

        // ── results_corrgram.csv ──────────────────────────────────────────────
        Map<String, double[]> cg = CsvFixtures.loadColumnar(
                "statsmodels/tsa/tests/results/results_corrgram.csv");
        refAcf     = cg.get("acvar");
        refAcfFft  = cg.get("acvarfft");
        refQStat   = cg.get("Q1");
        refPacfOls = cg.get("PACOLS");
        refPacfYw  = cg.get("PACYW");
        refConfLb  = cg.get("acvar_lb");
        refConfUb  = cg.get("acvar_ub");

        // ── results_ccf.csv ───────────────────────────────────────────────────
        refCcf = CsvFixtures.loadSingleColumn(
                "statsmodels/tsa/tests/results/results_ccf.csv");
    }


    // ═══════════════════════════════════════════════════════════════════════════
    // 1. AutoCovariance — acovf on realgdp
    //    Verified: FFT path == direct path to 8 decimal places
    // ═══════════════════════════════════════════════════════════════════════════

    @Test
    void acovfDirectAndFftAgree() {
        // statsmodels: acovf(realgdp, adjusted=False, demean=True, fft=False/True)
        // should agree to 8 decimal places
        double[] direct = AutoCovariance.compute(realgdp, false, true, false,
                MissingPolicy.NONE, 40);
        double[] fft    = AutoCovariance.compute(realgdp, false, true, true,
                MissingPolicy.NONE, 40);
        assertArrayEquals(direct, fft, TOL8, "acovf fft vs direct");
    }

    @Test
    void acovfDropMissingMatchesClean() {
        // statsmodels: acovf([NaN] + realgdp, missing='drop') == acovf(realgdp)
        double[] xnan = new double[realgdp.length + 1];
        xnan[0] = Double.NaN;
        System.arraycopy(realgdp, 0, xnan, 1, realgdp.length);
        double[] clean = AutoCovariance.compute(realgdp, false, true, false,
                MissingPolicy.NONE, 10);
        double[] drop  = AutoCovariance.compute(xnan, false, true, false,
                MissingPolicy.DROP, 10);
        assertArrayEquals(clean, drop, TOL8, "acovf drop missing");
    }

    @Test
    void acovfConservativeMissingMatchesClean() {
        // statsmodels: acovf([NaN] + realgdp, missing='conservative') == acovf(realgdp)
        double[] xnan = new double[realgdp.length + 1];
        xnan[0] = Double.NaN;
        System.arraycopy(realgdp, 0, xnan, 1, realgdp.length);
        double[] clean = AutoCovariance.compute(realgdp, false, true, false,
                MissingPolicy.NONE, 10);
        double[] cons  = AutoCovariance.compute(xnan, false, true, false,
                MissingPolicy.CONSERVATIVE, 10);
        assertArrayEquals(clean, cons, TOL8, "acovf conservative missing");
    }

    @Test
    void acovfRaisePolicyThrowsOnNaN() {
        // statsmodels: acovf([NaN]+x, missing='raise') raises MissingDataError
        double[] xnan = new double[realgdp.length + 1];
        xnan[0] = Double.NaN;
        System.arraycopy(realgdp, 0, xnan, 1, realgdp.length);
        assertThrows(IllegalArgumentException.class, () ->
                AutoCovariance.compute(xnan, false, true, false,
                        MissingPolicy.RAISE, null));
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 2. AutoCorrelation (ACF) — against results_corrgram.csv
    //    Source: statsmodels/tsa/tests/test_stattools.py::TestACF
    //    Reference: Stata corrgram.do on macrodata["realgdp"]
    // ═══════════════════════════════════════════════════════════════════════════

    @Test
    void acfDirectMatchesStata() {
        // statsmodels: acf(realgdp, nlags=40, fft=False)[1:41] == results_corrgram["acvar"]
        // Precision: DECIMAL_8
        AutoCorrelation r = AutoCorrelation.compute(realgdp, false, 40, false, false,
                null, true, MissingPolicy.NONE);
        assertArrayEquals(refAcf, slice(r.acf(), 1, 41), TOL8, "acf direct vs Stata");
    }

    @Test
    void acfFftMatchesStata() {
        // statsmodels: acf(realgdp, nlags=40, fft=True)[1:] == results_corrgram["acvarfft"]
        AutoCorrelation r = AutoCorrelation.compute(realgdp, false, 40, false, true,
                null, true, MissingPolicy.NONE);
        assertArrayEquals(refAcfFft, slice(r.acf(), 1, 41), TOL8, "acf fft vs Stata");
    }

    @Test
    void acfQStatMatchesStata() {
        // statsmodels: acf(realgdp, nlags=40, qstat=True)[2][:40] == results_corrgram["Q1"]
        // Precision: DECIMAL_3 (Stata rounding)
        AutoCorrelation r = AutoCorrelation.compute(realgdp, false, 40, true, false,
                null, true, MissingPolicy.NONE);
        assertArrayEquals(refQStat, r.qStat(), TOL3, "acf Q-stat vs Stata");
    }

    @Test
    void acfBartlettConfIntMatchesStata() {
        // statsmodels: centered confint[1:41] == results_corrgram[["acvar_lb","acvar_ub"]]
        // Precision: DECIMAL_8
        AutoCorrelation r = AutoCorrelation.compute(realgdp, false, 40, false, false,
                0.05, true, MissingPolicy.NONE);
        assertNotNull(r.confInt());
        Double2[] ci = r.confInt();
        for (int i = 1; i <= 40; i++) {
            double mean = (ci[i].lower() + ci[i].upper()) / 2.0;
            double lb = ci[i].lower() - mean;
            double ub = ci[i].upper() - mean;
            assertEquals(refConfLb[i - 1], lb, TOL8, "confint lb lag=" + i);
            assertEquals(refConfUb[i - 1], ub, TOL8, "confint ub lag=" + i);
        }
    }

    @Test
    void acfNoneNaNPropagates() {
        // statsmodels: acf([NaN]+realgdp, missing='none')[1:41] are all NaN
        double[] xnan = new double[realgdp.length + 1];
        xnan[0] = Double.NaN;
        System.arraycopy(realgdp, 0, xnan, 1, realgdp.length);
        AutoCorrelation r = AutoCorrelation.compute(xnan, false, 40, false, false,
                null, true, MissingPolicy.NONE);
        for (int i = 1; i < r.acf().length; i++) {
            assertTrue(Double.isNaN(r.acf()[i]), "acf[" + i + "] should be NaN");
        }
    }

    @Test
    void acfDropMissingMatchesClean() {
        // statsmodels: acf([NaN]+realgdp, missing='drop')[1:41] == results_corrgram["acvar"]
        double[] xnan = new double[realgdp.length + 1];
        xnan[0] = Double.NaN;
        System.arraycopy(realgdp, 0, xnan, 1, realgdp.length);
        AutoCorrelation r = AutoCorrelation.compute(xnan, false, 40, false, false,
                null, true, MissingPolicy.DROP);
        assertArrayEquals(refAcf, slice(r.acf(), 1, 41), TOL8, "acf drop missing");
    }

    @Test
    void acfConservativeMissingMatchesClean() {
        // statsmodels: acf([NaN]+realgdp, missing='conservative')[1:41] == results_corrgram["acvar"]
        double[] xnan = new double[realgdp.length + 1];
        xnan[0] = Double.NaN;
        System.arraycopy(realgdp, 0, xnan, 1, realgdp.length);
        AutoCorrelation r = AutoCorrelation.compute(xnan, false, 40, false, false,
                null, true, MissingPolicy.CONSERVATIVE);
        assertArrayEquals(refAcf, slice(r.acf(), 1, 41), TOL8, "acf conservative missing");
    }


    // ═══════════════════════════════════════════════════════════════════════════
    // 3. PartialAutoCorrelation (PACF) — against results_corrgram.csv
    //    Source: statsmodels/tsa/tests/test_stattools.py::TestPACF
    //    Reference: Stata corrgram.do on macrodata["realgdp"]
    // ═══════════════════════════════════════════════════════════════════════════

    @Test
    void pacfOlsMatchesStata() {
        // statsmodels: pacf(realgdp, nlags=40, method='ols')[1:] == results_corrgram["PACOLS"]
        // Precision: DECIMAL_6
        PartialAutoCorrelation r = PartialAutoCorrelation.compute(
                realgdp, 40, PartialAutoCorrelation.Method.OLS, null);
        assertArrayEquals(refPacfOls, slice(r.pacf(), 1, 41), TOL6, "pacf OLS vs Stata");
    }

    @Test
    void pacfOlsConfIntCenteredHalfWidth() {
        // statsmodels: centered confint half-width = 0.1375625 for all lags (1/sqrt(n))
        // from edited Stata ado file
        PartialAutoCorrelation r = PartialAutoCorrelation.compute(
                realgdp, 40, PartialAutoCorrelation.Method.OLS, 0.05);
        assertNotNull(r.confInt());
        Double2[] ci = r.confInt();
        // lag 0: confint == [1, 1]
        assertEquals(1.0, ci[0].lower(), TOL12);
        assertEquals(1.0, ci[0].upper(), TOL12);
        // lags 1..40: centered half-width == 0.1375625
        for (int i = 1; i <= 40; i++) {
            double mean = (ci[i].lower() + ci[i].upper()) / 2.0;
            double hw = ci[i].upper() - mean;
            assertEquals(0.1375625, hw, TOL6, "pacf OLS confint hw lag=" + i);
        }
    }

    @Test
    void pacfYwMatchesStata() {
        // statsmodels: pacf_yw(realgdp, nlags=40, method='mle')[1:] == results_corrgram["PACYW"]
        // Precision: DECIMAL_8
        PartialAutoCorrelation r = PartialAutoCorrelation.compute(
                realgdp, 40, PartialAutoCorrelation.Method.YW_MLE, null);
        assertArrayEquals(refPacfYw, slice(r.pacf(), 1, 41), TOL8, "pacf YW vs Stata");
    }

    @Test
    void pacfLdAdjustedMatchesYwAdjusted() {
        // statsmodels: pacf(x, method='lda') == pacf(x, method='yw')
        PartialAutoCorrelation yw = PartialAutoCorrelation.compute(
                realgdp, 40, PartialAutoCorrelation.Method.YW_ADJUSTED, null);
        PartialAutoCorrelation ld = PartialAutoCorrelation.compute(
                realgdp, 40, PartialAutoCorrelation.Method.LD_ADJUSTED, null);
        assertArrayEquals(yw.pacf(), ld.pacf(), TOL8, "pacf LD_adjusted == YW_adjusted");
    }

    @Test
    void pacfLdBiasedMatchesYwMle() {
        // statsmodels: pacf(x, method='ldb') == pacf_yw(x, method='mle')
        PartialAutoCorrelation yw = PartialAutoCorrelation.compute(
                realgdp, 40, PartialAutoCorrelation.Method.YW_MLE, null);
        PartialAutoCorrelation ld = PartialAutoCorrelation.compute(
                realgdp, 40, PartialAutoCorrelation.Method.LD_BIASED, null);
        assertArrayEquals(yw.pacf(), ld.pacf(), TOL8, "pacf LD_biased == YW_mle");
    }

    @Test
    void pacfBurgMatchesFacade() {
        // statsmodels: pacf_burg(realgdp, nlags=40) == pacf(realgdp, method='burg')
        // Both should return the same values
        PartialAutoCorrelation r1 = PartialAutoCorrelation.compute(
                realgdp, 40, PartialAutoCorrelation.Method.BURG, null);
        // Verify lag-0 is always 1
        assertEquals(1.0, r1.pacf()[0], TOL12);
        // Verify lag-1 is close to the YW estimate (both should be near 0.987)
        assertEquals(refPacfYw[0], r1.pacf()[1], 0.02, "pacf Burg lag1 near YW");
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 4. CrossCorrelation (CCF) — against results_ccf.csv
    //    Source: statsmodels/tsa/tests/test_stattools.py::TestCCF
    //    Input: unemp.diff() vs infl.diff() from macrodata
    // ═══════════════════════════════════════════════════════════════════════════

    @Test
    void ccfMatchesStata() {
        // statsmodels: ccf(unemp.diff, infl.diff, nlags=20, adjusted=False, fft=False)
        // == results_ccf.csv
        // Precision: DECIMAL_8
        double[] actual = CrossCorrelation.compute(
                unempDiff, inflDiff, false, false, 20, null).ccf();
        assertArrayEquals(refCcf, actual, TOL8, "ccf vs Stata");
    }

    @Test
    void ccfConfIntSymmetric() {
        // statsmodels: confint is symmetric around ccf values
        // alpha1 = norm.cdf(halfwidth / (1/sqrt(n))) should equal 1 - alpha/2
        double alpha = 0.05;
        CrossCorrelation r = CrossCorrelation.compute(
                unempDiff, inflDiff, false, false, 20, alpha);
        assertNotNull(r.confInt());
        double[] ccf = r.ccf();
        Double2[] ci = r.confInt();
        for (int i = 0; i < ccf.length; i++) {
            double lbDist = ccf[i] - ci[i].lower();
            double ubDist = ci[i].upper() - ccf[i];
            assertEquals(lbDist, ubDist, TOL8, "confint symmetric at lag=" + i);
        }
    }

    @Test
    void ccfFftMatchesDirect() {
        // FFT and direct paths should agree to 8 decimal places
        double[] direct = CrossCorrelation.compute(
                unempDiff, inflDiff, false, false, 20, null).ccf();
        double[] fft    = CrossCorrelation.compute(
                unempDiff, inflDiff, false, true,  20, null).ccf();
        assertArrayEquals(direct, fft, TOL8, "ccf fft vs direct");
    }

    @Test
    void correlateDirectModesMatchExpectedOverlapSemantics() {
        double[] a = {1.0, 2.0, 3.0, 4.0};
        double[] b = {5.0, 6.0, 7.0};

        assertArrayEquals(new double[] {38.0, 56.0},
                Correlate.correlate(a, b, Correlate.Mode.VALID, false), TOL12, "correlate valid");
        assertArrayEquals(new double[] {7.0, 20.0, 38.0, 56.0, 39.0, 20.0},
                Correlate.correlate(a, b, Correlate.Mode.FULL, false), TOL12, "correlate full");
        assertArrayEquals(new double[] {20.0, 38.0, 56.0, 39.0},
                Correlate.correlate(a, b, Correlate.Mode.SAME, false), TOL12, "correlate same");
    }

    @Test
    void correlateValidModePreservesShortLongOrientation() {
        double[] shortSeries = {5.0, 6.0, 7.0};
        double[] longSeries = {1.0, 2.0, 3.0, 4.0};

        assertArrayEquals(new double[] {56.0, 38.0},
                Correlate.correlate(shortSeries, longSeries, Correlate.Mode.VALID, false), TOL12,
                "correlate valid swapped");
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 5. LevinsonDurbin — on realgdp autocovariance
    //    Source: statsmodels/tsa/tests/test_stattools.py::TestLevinsonDurbin
    // ═══════════════════════════════════════════════════════════════════════════

    @Test
    void levinsonDurbinPacfMatchesYw() {
        // statsmodels: levinson_durbin(acovf(realgdp), nlags=40, isacov=True)
        // pacf == pacf_yw(realgdp, method='mle')
        double[] acov = AutoCovariance.compute(realgdp, false, true, false,
                MissingPolicy.NONE, 40);
        LevinsonDurbin ld = LevinsonDurbin.compute(acov, 40, true);
        // LD pacf[1:41] should match YW MLE pacf[1:41]
        assertArrayEquals(refPacfYw, slice(ld.pacf(), 1, 41), TOL8, "LD pacf vs YW");
    }

    @Test
    void levinsonDurbinSigmaVPositive() {
        double[] acov = AutoCovariance.compute(realgdp, false, true, false,
                MissingPolicy.NONE, 5);
        LevinsonDurbin r = LevinsonDurbin.compute(acov, 5, true);
        // statsmodels: sigma_v = 267655.5395360471
        assertEquals(267655.5395360471, r.sigmaV(), 1.0, "LD sigma_v");
        assertTrue(r.sigmaV() > 0);
    }

    @Test
    void levinsonDurbinArCoefficients() {
        // statsmodels: ar[:3] = [0.99081126, 0.01792568, 0.01774982]
        double[] acov = AutoCovariance.compute(realgdp, false, true, false,
                MissingPolicy.NONE, 5);
        LevinsonDurbin r = LevinsonDurbin.compute(acov, 5, true);
        assertEquals(0.99081126, r.arCoefs()[0], 1e-6, "LD ar[0]");
        assertEquals(0.01792568, r.arCoefs()[1], 1e-6, "LD ar[1]");
        assertEquals(0.01774982, r.arCoefs()[2], 1e-6, "LD ar[2]");
    }
    // ═══════════════════════════════════════════════════════════════════════════
    // Helpers
    // ═══════════════════════════════════════════════════════════════════════════

    /** Asserts element-wise equality with tolerance, printing the failing index. */
    private static void assertArrayEquals(double[] expected, double[] actual,
                                          double tol, String msg) {
        assertEquals(expected.length, actual.length, msg + " length");
        for (int i = 0; i < expected.length; i++) {
            assertEquals(expected[i], actual[i], tol, msg + "[" + i + "]");
        }
    }

    /** Returns {@code a[from..to-1]} as a new array. */
    private static double[] slice(double[] a, int from, int to) {
        double[] out = new double[to - from];
        System.arraycopy(a, from, out, 0, to - from);
        return out;
    }

    /** First-difference: {@code out[i] = a[i+1] - a[i]}. */
    private static double[] diff(double[] a) {
        double[] out = new double[a.length - 1];
        for (int i = 0; i < out.length; i++) out[i] = a[i + 1] - a[i];
        return out;
    }

}
