/*
 * Copyright (c) 2025 curioloop. All rights reserved.
 */
package com.curioloop.yum4j.optim.da;

/**
 * Reusable storage for dual annealing.
 *
 * <p>The workspace keeps the current annealing state, best solution, visiting proposal,
 * finite bounds, and strategy-chain state across iterations. Arrays are reused between
 * solves through {@link #ensure(int)} and {@link #reset()}.</p>
 */
public final class DAWorkspace {

    /** Number of decision variables. */
    int dimension;

    /** Current Markov-chain location accepted by annealing. */
    double[] current;

    /** Best location found so far; may be exposed as a live array to hooks. */
    double[] best;

    /** Proposed visiting location generated by {@link VisitingDistribution}. */
    double[] visit;

    /** Persistent state for SciPy-style strategy-chain local-search decisions. */
    StrategyChainState strategyChain;

    /** Objective value at {@link #current}. */
    double currentEnergy;

    /** Objective value at {@link #best}. */
    double bestEnergy;

    /** Diagnostic count of local-search invocations, mostly used by tests. */
    int localSearchRuns;

    /**
     * Ensures buffers are allocated for the requested dimension and local-search mode.
     *
     * <p>When local search is disabled, the strategy chain drops its minimum-tracking vector
     * because no local-search trigger can consume it. The current, best, and visit arrays are
     * retained across solves of the same dimension.</p>
     */
    public void ensure(int dimension, boolean localSearchEnabled) {
        if (dimension <= 0) throw new IllegalArgumentException("dimension must be positive");
        if (this.dimension == dimension && current != null) {
            strategyChain.ensure(dimension, localSearchEnabled);
            reset();
            return;
        }
        this.dimension = dimension;
        this.current = new double[dimension];
        this.best = new double[dimension];
        this.visit = new double[dimension];
        this.strategyChain = new StrategyChainState();
        this.strategyChain.ensure(dimension, localSearchEnabled);
        reset();
    }

    /** Clears scalar state while retaining arrays that are overwritten before use. */
    public void reset() {
        currentEnergy = Double.POSITIVE_INFINITY;
        bestEnergy = Double.POSITIVE_INFINITY;
        localSearchRuns = 0;
    }
}